### PR TITLE
Fix parametric test regression 

### LINKED ISSUE #1648: New test failure in parametric mixture
`test parametric mixture: Test Failed at /home/runner/work/IncrementalInference.jl/IncrementalInference.jl/test/testMixtureParametric.jl:54`

### PR DESCRIPTION
**Pull request by Affie**
close #1648

### CODE REVIEW

File: src/ParametricUtils.jl [hunk 1]
```diff
@@ -509,14 +509,8 @@ function solveGraphParametric(
   computeCovariance::Bool = true,
   solveKey::Symbol = :parametric,
   autodiff = :forward,
-  algorithm = Optim.NewtonTrustRegion, # Optim.BFGS,
```
Comment (Affie) [inline src/ParametricUtils.jl:512]: @dehann, just use the `algorithm` and `algorithmkwargs` keyword arguments if you want to use a different algorithm.

Comment (dehann) [reply src/ParametricUtils.jl:512]: alright, thanks.  I was testing stuff here.  Didn't realize you had explored the different algorithms to that extent yet.  Thanks for the fix
