### PR TITLE
Fix RobotFourDoor example

### LINKED ISSUE #882: problem with loading the example "RobotFourDoor.jl"
I'm trying to load this example but have the following issues:
- ERROR: UndefVarError: inferOverTree! not defined
- ERROR: UndefVarError: Odo not defined
- ERROR: UndefVarError: Obsv2 not defined

What can I do? I've updated the repository today.

Thanks in advance

### PR DESCRIPTION
**Pull request by Affie**
close #882

~~needs https://github.com/JuliaRobotics/RoMEPlotting.jl/pull/122~~

### CODE REVIEW

**Comment by Affie** [comment]
@dehann, I have it running, but it needs some work to be helpful to users. There are also unexported RoMEPlotting functions in use, maybe deprecated?

File: examples/RobotFourDoor.jl [hunk 1]
```diff
@@ -76,36 +77,28 @@ if true
...
 
 # do belief propagation inference over tree once
-[inferOverTree!(fg, tree, N=100) for i in 1:1];
+solveTree!(fg, tree)
 
 # draw all beliefs
 # TODO -- Update this part of the example
 using RoMEPlotting
 
-DOYTICKS = false
```
Comment (dehann) [inline examples/RobotFourDoor.jl:101]: yeah, please replace this part with just `plotKDE` which can take vector inputs

Comment (dehann) [reply examples/RobotFourDoor.jl:101]: deprecate the older stuff, thanks!
