### PR TITLE
fix solveFactorMeasurements

### LINKED ISSUE #1009: Intermittent error in  `addLikelihoodsDifferential!` (solveFactorMeasurements)
Here is a way to repeat the error. It uses julia serialization, so will be version dependant. 
Save file [issue_1009.log](https://github.com/JuliaRobotics/IncrementalInference.jl/files/5458701/issue_1009.log)
and run this until error is thrown:
```julia
using Serialization
using IncrementalInference
using RoME

(cliqSubFg, beliefMsg) = deserialize("issue_1009.log")

for i = 1:10
    subfg = deepcopy(cliqSubFg)
    addLikelihoodsDifferential!(subfg, beliefMsg)
end
```

```julia 
julia> addLikelihoodsDifferential!(csmc19.cliqSubFg, beliefMsg)
ERROR: BoundsError: attempt to access 2×1 Array{Float64,2} at index [1:2, 61]
Stacktrace:
 [1] throw_boundserror(::Array{Float64,2}, ::Tuple{Base.Slice{Base.OneTo{Int64}},Int64}) at ./abstractarray.jl:541
 [2] checkbounds at ./abstractarray.jl:506 [inlined]
 [3] _getindex at ./multidimensional.jl:742 [inlined]
 [4] getindex(::Array{Float64,2}, ::Function, ::Int64) at ./abstractarray.jl:1060
 [5] solveFactorMeasurements(::LightDFG{SolverParams,DFGVariable,DFGFactor}, ::Symbol, ::Symbol) at /home/johan/.julia/dev/IncrementalInference/src/DeconvUtils.jl:64
 [6] solveFactorMeasurements at /home/johan/.julia/dev/IncrementalInference/src/DeconvUtils.jl:31 [inlined]
 [7] addLikelihoodsDifferential!(::LikelihoodMessage{IncrementalInference.NonparametricMessage}, ::LightDFG{SolverParams,DFGVariable,DFGFactor}, ::LightDFG{SolverParams,DFGVariable,DFGFactor}) at /home/johan/.julia/dev/IncrementalInference/src/TreeMessageUtils.jl:164
 [8] addLikelihoodsDifferential! at /home/johan/.julia/dev/IncrementalInference/src/TreeMessageUtils.jl:139 [inlined]
 [9] addLikelihoodsDifferential!(::LightDFG{SolverParams,DFGVariable,DFGFactor}, ::LikelihoodMessage{IncrementalInference.NonparametricMessage}) at /home/johan/.julia/dev/IncrementalInference/src/TreeMessageUtils.jl:176
 [10] top-level scope at REPL[208]:1
```

_Originally posted by @Affie in https://github.com/JuliaRobotics/RoME.jl/issues/344#issuecomment-718610748_

### PR DESCRIPTION
**Pull request by Affie**
close #1009

### CODE REVIEW

File: src/DeconvUtils.jl [hunk 1]
```diff
@@ -61,7 +61,7 @@ function solveFactorMeasurements(dfg::AbstractDFG,
         if !r.g_converged
           nsm = getSample(fcttype, 1)
           for count in 1:length(meas)
```
Comment (dehann) [inline src/DeconvUtils.jl:63]: wow, okay good catch.  Now I'm wondering if this `length(meas)` is right?  `meas::Tuple`, but element `idx` is usually element of `size(meas[1],2)`

Comment (dehann) [reply src/DeconvUtils.jl:63]: ah wait that is right

Comment (dehann) [reply src/DeconvUtils.jl:63]: already have `idx = 1:N` as outer loop

Comment (dehann) [reply src/DeconvUtils.jl:63]: this is all right

Comment (dehann) [reply src/DeconvUtils.jl:63]: actually wait

**Review by dehann — CHANGES_REQUESTED** [review]
the original code might be right?

File: src/DeconvUtils.jl [hunk 2]
```diff
@@ -61,7 +61,7 @@ function solveFactorMeasurements(dfg::AbstractDFG,
...
-            meas[count][:,idx] = nsm[count][:,idx]
+            meas[count][:,idx] = nsm[count][:,1]
```
Comment (dehann) [inline src/DeconvUtils.jl:64]: yes, put into idx the single value, i.e. 1

**Review by dehann — APPROVED** [review]
